version: '2'
services:
    monmedecin-app:
        image: monmedecin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://monmedecin-mysql:3306/monmedecin?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=monmedecin-elasticsearch:9300
        ports:
            - 8080:8080
    monmedecin-mysql:
        extends:
            file: mysql.yml
            service: monmedecin-mysql
    monmedecin-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: monmedecin-elasticsearch
